### ISSUE TITLE
Full Node Miner Supervene Config Not Mining on All Cores

### ISSUE THREAD

**Issue by tstoll** [hacash/miner#1]
After the recent update back in mid-May, full node miners are not mining at "full throttle" as set by their supervene param in the config file. It will always mine with only 1 core regardless of what the supervene param is set to.

For example, if I mine with a 48 core processor and set supervene = 48 then only a single (1) core will mine.

**Comment by jojoin** [comment]
I am sorry for late. You're the first to make issues.

The error has been fixed in the latest version.

Download latest Full Node Miner: http://download.hacash.org:8080/miner_node_hacash_ubuntu64.zip

**Comment by tstol002** [comment]
Sorry for my late response as well! I switched accounts and never received a notification of your response.

Thank you you for your responsiveness. Issue confirmed fixed.
