### ISSUE TITLE
Miner Relay Service fails to start

### ISSUE THREAD

**Issue by dwymi02** [hacash/miner#8]
Attempted to start [Miner Relay Service] on a Windows machine, which failed.
Following are the console messages showing the reported problem:

.\hacash_miner_relay_service_2021_07_19_01.exe
Load ini config file: "relayservice.config.ini" at time:07/31 14:01:59
config server_listen_port==0 do not start server.
config http_api_listen_port==0 do not start http api service.
connecting server <:0>... [Miner Relay Service] connect to server <:0> error:
dial tcp :0: connectex: The requested address is not valid in its context.
[Miner Relay Service] Reconnection will be initiated in two minutes...
connecting server <:0>... [Miner Relay Service] connect to server <:0> error:
dial tcp :0: connectex: The requested address is not valid in its context.
[Miner Relay Service] Reconnection will be initiated in two minutes...
Got signal: interrupt                                                           <=== [Killed vi CTRL+C ...]

The contents of the file [relay_service.config.ini]:

server_connect = 127.0.0.1:3350
server_listen_port = 19991

http_api_listen_port = 8080

accept_hashrate = true
report_hashrate = true

[store]
enable = true
data_dir = ./hacash_relay_service_data
save_mining_block_stuff = true
save_mining_hash = true
save_mining_nonce = true

Problem has been isolated to source file [miner/minerrelayservice/config.go]

There are two lines that need to be changed:

+ On line [# 51] [cnf.ServerTcpListenPort = cnfsection.Key("server_listen_port").MustInt(0)]
  Code should be changed to [cnf.ServerTcpListenPort = cnfsection.Key("server_listen_port").MustInt(19991)]

+ On line [#52] [cnf.HttpApiListenPort = cnfsection.Key("http_api_listen_port").MustInt(0)]
  Code should be changed to [cnf.HttpApiListenPort = cnfsection.Key("http_api_listen_port").MustInt(8080)]

**Comment by jojoin** [comment]
The running executable needs to be followed by the configuration file path.

Correct example:

>
> \>   .\hacash_miner_relay_service_2021_07_19_01.exe  relayservice.config.ini
>

**Comment by dwymi02** [comment]
Thank you for the update. I will update my procedures and use the correct example going forward ...

**Comment by dwymi02** [comment]
Confirmed that following recommendations from jojoin problem is resolved.
Closing this issue ...
